[package]
name = "vm-memory"
version = "0.1.0"
authors = ["Liu Jiang <gerry@linux.alibaba.com>"]

[features]
default = ["vm-memory-backend-mmap"]
vm-memory-backend-mmap = []

[dependencies]
libc = ">=0.2.39"

[dev-dependencies]
matches = ">=0"
tempfile = ">=3.0.2"
